# Generated by Django 5.1.7 on 2026-01-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_invoice_alter_payment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="direction",
            field=models.CharField(default="Incoming", max_length=255),
        ),
    ]
