# Generated by Django 5.1.7 on 2026-01-28 10:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_branch_branch_manager"),
        ("payments", "0006_payment_branch_payment_business"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ORDER", "Order"),
                            ("INVOICE", "Invoice"),
                            ("PAYMENT", "Payment"),
                            ("EXPENSE", "Expense"),
                            ("ADJUSTMENT", "Adjustment"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SALE", "Sale"),
                            ("REFUND", "Refund"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("EXPENSE_PAID", "Expense Paid"),
                            ("WRITE_OFF", "Write-off"),
                            ("MANUAL_ADJUSTMENT", "Manual Adjustment"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledgers",
                        to="core.branch",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledgers",
                        to="core.business",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "date"],
                        name="payments_bu_busines_bbc9d2_idx",
                    ),
                    models.Index(
                        fields=["branch", "date"], name="payments_bu_branch__0ac08f_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("credit", 0), ("debit__gt", 0)),
                            models.Q(("credit__gt", 0), ("debit", 0)),
                            _connector="OR",
                        ),
                        name="only_one_of_debit_or_credit",
                    )
                ],
            },
        ),
    ]
