# Generated by Django 5.1.7 on 2026-01-28 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_branch_branch_manager"),
        ("invoices", "0008_supplierinvoice_purchase_order"),
        ("payments", "0007_businessledger"),
        ("supplychain", "0004_purchaseorderitem_received_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField()),
                ("payment_method", models.CharField(max_length=255)),
                ("reference_number", models.CharField(max_length=255, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branchsupplierpayments",
                        to="core.branch",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="businesssupplierpayments",
                        to="core.business",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplierpayments",
                        to="supplychain.supplier",
                    ),
                ),
                (
                    "supplier_invoice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplierinvoicepayments",
                        to="invoices.supplierinvoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
