# Generated by Django 5.1.7 on 2026-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_supplierpayment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessledger",
            name="description",
        ),
        migrations.AlterField(
            model_name="businessledger",
            name="reason",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="businessledger",
            name="record_type",
            field=models.CharField(
                choices=[("Debit", "Debit"), ("Credit", "Credit")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="businessledger",
            name="source",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
