# Generated by Django 5.1.7 on 2026-01-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_remove_businessledger_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessledger",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
