# Generated by Django 5.1.7 on 2026-02-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_businessledger_description"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="businessledger",
            name="only_one_of_debit_or_credit",
        ),
    ]
