# Generated by Django 5.1.7 on 2026-02-03 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0011_alter_invoice_status"),
        ("payments", "0011_remove_businessledger_only_one_of_debit_or_credit"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerInvoicePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=100)),
                ("payment_method", models.CharField(max_length=255)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
