# Generated by Django 5.1.7 on 2026-02-03 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_branch_branch_manager"),
        ("invoices", "0011_alter_invoice_status"),
        ("payments", "0012_customerinvoicepayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerinvoicepayment",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_payments",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="customerinvoicepayment",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_payments",
                to="core.business",
            ),
        ),
        migrations.AlterField(
            model_name="customerinvoicepayment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_payments",
                to="invoices.invoice",
            ),
        ),
    ]
