# Generated by Django 5.1.7 on 2026-02-11 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bnpl", "0005_alter_bnplpurchase_service_provider"),
        ("payments", "0014_mpesatransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="BNPLInstallmentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField()),
                ("payment_method", models.CharField(max_length=255)),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installment_payments",
                        to="bnpl.bnplinstallment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
