# Generated by Django 5.1.7 on 2026-02-11 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bnpl", "0005_alter_bnplpurchase_service_provider"),
        ("core", "0008_alter_branch_branch_manager"),
        ("payments", "0015_bnplinstallmentpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="bnplinstallmentpayment",
            name="bnpl_provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installment_payments",
                to="bnpl.bnplserviceprovider",
            ),
        ),
        migrations.AddField(
            model_name="bnplinstallmentpayment",
            name="bnpl_purchase",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installment_payments",
                to="bnpl.bnplpurchase",
            ),
        ),
        migrations.AddField(
            model_name="bnplinstallmentpayment",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installment_payments",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="bnplinstallmentpayment",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installment_payments",
                to="core.business",
            ),
        ),
    ]
