# Generated by Django 5.1.7 on 2026-02-11 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bnpl", "0005_alter_bnplpurchase_service_provider"),
        ("payments", "0017_alter_bnplinstallmentpayment_bnpl_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="installment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installment_payments",
                to="bnpl.bnplinstallment",
            ),
        ),
        migrations.DeleteModel(
            name="BNPLInstallmentPayment",
        ),
    ]
