# Generated by Django 5.1.7 on 2026-02-11 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bnpl", "0005_alter_bnplpurchase_service_provider"),
        ("core", "0008_alter_branch_branch_manager"),
        ("customers", "0013_giftcard_status"),
        ("payments", "0018_payment_installment_delete_bnplinstallmentpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="BNPLInstallmentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField()),
                ("payment_method", models.CharField(max_length=255)),
                ("reference_number", models.CharField(max_length=255)),
                ("payment_type", models.CharField(max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_installment_payments",
                        to="core.branch",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_installment_payments",
                        to="core.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_installment_payments",
                        to="customers.loyaltycard",
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_installment_payments",
                        to="bnpl.bnplinstallment",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_installment_payments",
                        to="bnpl.bnplpurchase",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_installment_payments",
                        to="bnpl.bnplserviceprovider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
