# Generated by Django 5.1.7 on 2026-02-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_bnplinstallmentpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessledger",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
