hello = {
    'items': [{'id': 9, 'item_name': 'Orange Juice', 'quantity': 1, 'unit_price': 150, 'total_price': 150}, 
              {'id': 8, 'item_name': 'Eggs 12pc', 'quantity': 1, 'unit_price': 360, 'total_price': 360}, 
              {'id': 7, 'item_name': 'Rice 5kg', 'quantity': 1, 'unit_price': 1500, 'total_price': 1500}
            ], 'subtotal': 2010, 
            'tax': 161, 
            'total': 2171, 
            'paymentMethod': 'bnpl', 
            'amountReceived': 2171, 
            'change': 0, 
            'mobileNumber': '', 
            'mobileNetwork': '', 
            'splitCashAmount': 0, 
            'splitMobileAmount': 0, 
            'bnplDownPayment': 218, 
            'bnplInstallments': 50, 
            'bnplInterval': 1, 
            'downPaymentMethod': 'Bank Transfer', 
            'bnplServiceProvider': 1, 
            'bnplPerPaymentAmount': 42, 
            'bnplRemainingPaymentAmount': 2063, 
            'customerId': 2, 
            'customerName': 'John Doe', 
            'cardNumber': '', 
            'storeCreditUsed': 0, 
            'storeCreditBalance': 0, 
            'loyaltyPointsUsed': 0, 
            'loyaltyPointsBalance': 0, 
            'loyaltyPointsRate': 1, 
            'status': 'Pending', 
            'date': '2026-01-29', 
            'receiptNo': '95423'}
