# Generated by Django 5.1.7 on 2026-01-29 12:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_alter_branch_branch_manager"),
        ("customers", "0013_giftcard_status"),
        ("orders", "0008_order_branch_orderitem_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="BNPLPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("down_payment", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bnpl_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                ("number_of_installments", models.PositiveIntegerField()),
                ("payment_interval_days", models.PositiveIntegerField()),
                ("status", models.CharField(default="Active", max_length=50)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_purchases",
                        to="core.branch",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_purchases",
                        to="core.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.loyaltycard",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BNPLInstallment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("installment_number", models.PositiveIntegerField()),
                (
                    "amount_expected",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("due_date", models.DateTimeField()),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="Pending", max_length=50)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_installments",
                        to="core.branch",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_installments",
                        to="core.business",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bnpl.bnplpurchase",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BNPLServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "down_payment_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "interest_rate_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_service_providers",
                        to="core.branch",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bnpl_service_providers",
                        to="core.business",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="bnplpurchase",
            name="service_provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="bnpl.bnplserviceprovider",
            ),
        ),
    ]
