# Generated by Django 5.1.7 on 2026-01-29 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bnpl", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bnplinstallment",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installments",
                to="bnpl.bnplpurchase",
            ),
        ),
    ]
