# Generated by Django 5.1.7 on 2026-01-29 13:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bnpl", "0002_alter_bnplinstallment_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="bnplpurchase",
            name="installment_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
