# Generated by Django 5.1.7 on 2026-01-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bnpl", "0003_bnplpurchase_installment_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bnplinstallment",
            name="installment_number",
        ),
    ]
