# Generated by Django 5.1.7 on 2026-02-09 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bnpl", "0004_remove_bnplinstallment_installment_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bnplpurchase",
            name="service_provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bnpl_purchases",
                to="bnpl.bnplserviceprovider",
            ),
        ),
    ]
