# Generated by Django 5.1.7 on 2026-02-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bnpl", "0005_alter_bnplpurchase_service_provider"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bnplinstallment",
            options={"ordering": ["paid_installment", "due_date"]},
        ),
        migrations.AddField(
            model_name="bnplinstallment",
            name="paid_installment",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
