# Generated by Django 5.1.7 on 2026-01-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("orders", "0003_remove_orderitem_item_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
