# Generated by Django 5.1.7 on 2026-01-03 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0003_category_inventoryitem_barcode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone_number", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255, null=True)),
                ("due_date", models.DateField()),
                ("invoice_number", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.FloatField(default=1)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.invoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventoryitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
