# Generated by Django 5.1.7 on 2026-01-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_invoiceitem_item_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="sub_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
