# Generated by Django 5.1.7 on 2026-01-27 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_branch"),
        ("invoices", "0004_invoice_sub_total_invoice_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branchinvoices",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businessinvoices",
                to="core.business",
            ),
        ),
    ]
