# Generated by Django 5.1.7 on 2026-01-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0006_supplierinvoice_supplierinvoiceitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierinvoice",
            name="invoice_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
