# Generated by Django 5.1.7 on 2026-01-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0007_alter_supplierinvoice_invoice_number"),
        ("supplychain", "0004_purchaseorderitem_received_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierinvoice",
            name="purchase_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplierinvoices",
                to="supplychain.purchaseorder",
            ),
        ),
    ]
