# Generated by Django 5.1.7 on 2026-01-29 10:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0008_supplierinvoice_purchase_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierinvoice",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
