# Generated by Django 5.1.7 on 2026-02-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0009_supplierinvoice_amount_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(default="Pending", max_length=255),
        ),
    ]
