# Generated by Django 5.1.7 on 2026-02-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0010_alter_invoice_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Payment", "Pending Payment"),
                    ("Paid", "Paid"),
                    ("Cancelled", "Cancelled"),
                    ("Declined", "Declined"),
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
