# Generated by Django 5.1.7 on 2026-02-03 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_branch_branch_manager"),
        ("invoices", "0012_alter_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierinvoiceitem",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branchsupplierinvoicesitems",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="supplierinvoiceitem",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesssupplierinvoicesitems",
                to="core.business",
            ),
        ),
    ]
