# Generated by Django 5.1.7 on 2026-01-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="customer_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
