# Generated by Django 5.1.7 on 2026-01-04 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_invoice_sub_total_invoice_tax"),
        ("orders", "0006_rename_price_orderitem_item_total_and_more"),
        ("payments", "0003_payment_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoicepayments",
                to="invoices.invoice",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderpayments",
                to="orders.order",
            ),
        ),
    ]
