# Generated by Django 5.1.7 on 2026-01-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LoyaltyCardRechareg",
            new_name="LoyaltyCardRecharge",
        ),
    ]
