# Generated by Django 5.1.7 on 2026-01-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_rename_loyaltycardrechareg_loyaltycardrecharge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcard",
            name="customer_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="giftcard",
            name="phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
