# Generated by Django 5.1.7 on 2026-01-06 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_giftcard_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loyaltycardrecharge",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recharges",
                to="customers.loyaltycard",
            ),
        ),
        migrations.AlterField(
            model_name="loyaltycardredeem",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redeems",
                to="customers.loyaltycard",
            ),
        ),
    ]
