# Generated by Django 5.1.7 on 2026-01-06 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_giftcardrecharge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftcardrecharge",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recharges",
                to="customers.giftcard",
            ),
        ),
        migrations.AlterField(
            model_name="giftcardredeem",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redeems",
                to="customers.giftcard",
            ),
        ),
    ]
