# Generated by Django 5.1.7 on 2026-01-27 13:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_alter_giftcardrecharge_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loyaltycard",
            name="available_credit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="loyaltycard",
            name="total_store_credit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("100000"), max_digits=10
            ),
        ),
    ]
