# Generated by Django 5.1.7 on 2026-01-27 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_branch"),
        ("customers", "0007_loyaltycard_available_credit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loyaltycard",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branchloyaltycards",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="loyaltycardrecharge",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branchloyaltycardrecharges",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="loyaltycardrecharge",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businessloyaltycardrecharges",
                to="core.business",
            ),
        ),
        migrations.AddField(
            model_name="loyaltycardredeem",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branchloyaltycardredeems",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="loyaltycardredeem",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businessloyaltycardredeems",
                to="core.business",
            ),
        ),
        migrations.AlterField(
            model_name="loyaltycard",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businessloyaltycards",
                to="core.business",
            ),
        ),
    ]
