# Generated by Django 5.1.7 on 2026-01-29 05:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_loyaltycard_branch_loyaltycardrecharge_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loyaltycard",
            name="available_credit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("100000"), max_digits=10
            ),
        ),
    ]
