# Generated by Django 5.1.7 on 2026-01-29 06:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0009_alter_loyaltycard_available_credit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loyaltycard",
            old_name="total_store_credit",
            new_name="credit_limit",
        ),
        migrations.AddField(
            model_name="loyaltycard",
            name="credit_issued",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
