# Generated by Django 5.1.7 on 2026-01-29 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_branch_branch_manager"),
        (
            "customers",
            "0010_rename_total_store_credit_loyaltycard_credit_limit_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcard",
            name="customer_email",
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="giftcard",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="giftcard",
            name="branch",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="core.branch"
            ),
        ),
    ]
