# Generated by Django 5.1.7 on 2026-01-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0011_remove_giftcard_customer_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="giftcard",
            old_name="initial_balance",
            new_name="amount",
        ),
    ]
