# Generated by Django 5.1.7 on 2026-01-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_rename_initial_balance_giftcard_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftcard",
            name="status",
            field=models.CharField(default="Active", max_length=50),
        ),
    ]
