# Generated by Django 5.1.7 on 2026-01-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_alter_invoiceitem_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceitem",
            name="item_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
