# Generated by Django 5.1.7 on 2026-01-27 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_branch"),
        ("users", "0003_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branchusers",
                to="core.branch",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="businessusers",
                to="core.business",
            ),
        ),
    ]
