# Generated by Django 5.1.7 on 2026-01-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderitem_inventory_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="item_name",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="menu_item",
        ),
    ]
