# Generated by Django 5.1.7 on 2026-01-04 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_business_business_type_business_city_and_more"),
        ("orders", "0003_remove_orderitem_item_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.business",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.business",
            ),
        ),
    ]
