# Generated by Django 5.1.7 on 2026-01-04 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_business_business_type_business_city_and_more"),
        ("orders", "0004_order_business_orderitem_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="businessorders",
                to="core.business",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.business"
            ),
        ),
    ]
