# Generated by Django 5.1.7 on 2026-01-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_menu_remove_inventoryitem_price_and_more"),
        ("orders", "0006_rename_price_orderitem_item_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="menu_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.menu",
            ),
        ),
    ]
