# Generated by Django 5.1.7 on 2026-01-27 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_branch"),
        ("orders", "0007_orderitem_menu_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branchorders",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.branch",
            ),
        ),
    ]
