# Generated by Django 5.1.7 on 2026-02-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_amount_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("BNPL", "BNPL"), ("Paid", "Paid")],
                default="Paid",
                max_length=50,
            ),
        ),
    ]
