# Generated by Django 5.1.7 on 2026-01-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_category_inventoryitem_barcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="inventory.category",
            ),
        ),
    ]
