# Generated by Django 5.1.7 on 2026-01-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_inventoryitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
