# Generated by Django 5.1.7 on 2026-01-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_inventoryitem_business_inventorylog_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="restock_level",
            field=models.IntegerField(default=0),
        ),
    ]
