# Generated by Django 5.1.7 on 2026-01-28 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_inventoryitem_restock_level"),
        ("supplychain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplieditems",
                to="supplychain.supplier",
            ),
        ),
    ]
