# Generated by Django 5.1.7 on 2026-01-28 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_branch_branch_manager"),
        ("inventory", "0011_inventoryitem_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branchinventoryitems",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branchmenus",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businessmenus",
                to="core.business",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businessinventoryitems",
                to="core.business",
            ),
        ),
    ]
