# Generated by Django 5.1.7 on 2026-01-29 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_branch_branch_manager"),
        ("inventory", "0012_inventoryitem_branch_menu_branch_menu_business_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesscategories",
                to="core.business",
            ),
        ),
    ]
