# Generated by Django 5.1.7 on 2026-01-28 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_branch_branch_manager"),
        ("supplychain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsupplier",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branchproductsuppliers",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="productsupplier",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businessproductsuppliers",
                to="core.business",
            ),
        ),
    ]
