# Generated by Django 5.1.7 on 2026-01-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0002_productsupplier_branch_productsupplier_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
