# Generated by Django 5.1.7 on 2026-01-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0003_purchaseorderitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="received_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
