# Generated by Django 5.1.7 on 2026-01-29 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_branch_branch_manager"),
        ("supplychain", "0004_purchaseorderitem_received_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderitem",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branchpurchaseorderitems",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesspurchaseorderitems",
                to="core.business",
            ),
        ),
    ]
