# Generated by Django 5.1.7 on 2026-02-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplychain", "0005_purchaseorderitem_branch_purchaseorderitem_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(null=True),
        ),
    ]
