# Generated by Django 5.1.7 on 2026-01-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_business"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(default="Active", max_length=255),
        ),
    ]
