# Generated by Django 5.1.7 on 2025-12-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="currency",
            field=models.CharField(default="KES", max_length=10),
        ),
    ]
