# Generated by Django 5.1.7 on 2026-01-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_business_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="business_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="city",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="country",
            field=models.CharField(default="Kenya", max_length=255),
        ),
        migrations.AddField(
            model_name="business",
            name="owner_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="status",
            field=models.CharField(default="Active", max_length=255),
        ),
        migrations.AddField(
            model_name="business",
            name="tax_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
