# Generated by Django 5.1.7 on 2026-01-29 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_business_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="owner_name",
        ),
    ]
