# Generated by Django 5.1.7 on 2026-01-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="channel",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Credit Card", "Credit Card"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Mobile Payment", "Mobile Payment"),
                ],
                default="Bank Transfer",
                max_length=100,
            ),
        ),
    ]
