# Generated by Django 5.1.7 on 2026-01-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0004_alter_expense_channel"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pilot_period", models.IntegerField(default=30)),
                ("duration_days", models.IntegerField(default=30)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
