# Generated by Django 5.1.7 on 2026-01-29 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_branch_branch_manager"),
        ("finances", "0006_businesssubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.business",
            ),
        ),
    ]
