# Generated by Django 5.1.7 on 2026-01-29 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0009_rename_amount_storeloan_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeloanlog",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loanawards",
                to="finances.storeloan",
            ),
        ),
        migrations.AlterField(
            model_name="storeloanrepayment",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repayments",
                to="finances.storeloan",
            ),
        ),
    ]
