# Generated by Django 5.1.7 on 2026-01-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0010_alter_storeloanlog_loan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeloanrepayment",
            name="channel",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Credit Card", "Credit Card"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Mobile Money", "Mobile Money"),
                    ("Cheque", "Cheque"),
                ],
                default="Cash",
                max_length=100,
            ),
        ),
    ]
